global: &global
  themes:
    paths:
      checked_out: "public/themes/checked_out"
      private: "public/themes/private"
      cloud: "public/themes/cloud"
  notification_emails:
    - contato@austapp.com

development:
  <<: *global

test:
  <<: *global

staging:
  <<: *global

production:
  <<: *global
