global: &global
  google_analytics: false
  themes:
    paths:
      checked_out: "public/themes/checked_out"
      private: "public/themes/private"
      cloud: "public/themes/cloud"
  notification_emails:
    - devops@localhost

development:
  <<: *global

test:
  <<: *global
  themes:
    paths:
      test: "tmp/theme_files"
      checked_out: "public/themes/checked_out"
      private: "public/themes/private"
      cloud: "public/themes/cloud"

staging:
  <<: *global

production:
  <<: *global
  google_analytics: true
  s3:
    key_id: ""
    secret_access_key: ""
